version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: "postgres_luizalabs"
    environment:
      - POSTGRES_DB=schedule
      - POSTGRES_USER=luizalabs
      - POSTGRES_PASSWORD=luizalabs
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  tracking-api:
    image: 'docker-spring-boot-postgres:latest'
    build: .
    container_name: app
    depends_on:
      - postgres
    network_mode: "host"
    hostname: localhost
    restart: always
    ports:
      - 8082:8082
    healthcheck:
      test: "exit 0"
